#!/bin/bash

sudo true || exit 1

COLOR_DARK_GRAY="#464646"
COLOR_MEDIUM_GRAY="#6f6f6f"
COLOR_PINK="#f92472"
COLOR_GREEN="#a6e22c"
COLOR_WHITE="#f7f7f7"

set -x

sudo sed -i "s/#Color/Color/g" /etc/pacman.conf

curl -O https://download.sublimetext.com/sublimehq-pub.gpg
sudo pacman-key --add sublimehq-pub.gpg
sudo pacman-key --lsign-key 8A8F901A
sudo tee -a /etc/pacman.conf <<-EOF

	[sublime-text]
	Server = https://download.sublimetext.com/arch/stable/x86_64
EOF
rm sublimehq-pub.gpg

PACKAGES=(
	adobe-source-code-pro-fonts
	adobe-source-sans-pro-fonts
	adobe-source-serif-pro-fonts
	alacritty
	arc-gtk-theme
	arc-icon-theme
	bash-completion
	bc
	bind
	dmenu
	dmidecode
	dunst
	feh
	firefox
	flatpak
	gimp
	git
	gnome-themes-extra # Arc theme dependency
	gpicview
	gtk-engine-murrine # Arc theme dependency
	gvfs
	gvfs-mtp
	gvfs-nfs
	gvfs-smb
	htop
	i3-wm
	i3status
	jq
	libnewt
	libnotify
	libreoffice-fresh
	lsof
	man
	mkvtoolnix-cli
	mpv
	nmap
	numlockx
	openssh
	p7zip
	pass
	pavucontrol
	pcmanfm
	pipewire
	pipewire-pulse
	polkit
	pwgen
	python
	python-virtualenv
	ripgrep
	rsync
	scrot
	slock
	sshfs
	sublime-text
	tcpdump
	testdisk
	thunderbird
	ttf-liberation
	ufw
	unrar
	unzip
	wget
	wireplumber
	xclip
	xcursor-vanilla-dmz
	xdg-desktop-portal # Flapak dependency
	xdg-desktop-portal-gtk # Flapak dependency
	xorg-server
	xorg-xinit
	xorg-xrandr
	xorg-xsetroot
	xss-lock
	xterm
	zip
)
sudo pacman --noconfirm -Sy "${PACKAGES[@]}"

flatpak remote-add --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo

curl -O https://dn-works.com/wp-content/uploads/2020/UFAS-Fonts/Symbola.zip
sudo mkdir -p /usr/share/fonts/ancient-scripts
sudo unzip -d /usr/share/fonts/ancient-scripts Symbola.zip Symbola.otf
rm Symbola.zip

sudo perl -pi -e "s/#CC3333/${COLOR_MEDIUM_GRAY^^}/g;" -e "s/#005577/${COLOR_GREEN^^}/g;" /usr/bin/slock
sudo tee /etc/pacman.d/hooks/20-slock.hook <<-EOF
	[Trigger]
	Type = Package
	Operation = Upgrade
	Target = slock

	[Action]
	When = PostTransaction
	Exec = /usr/bin/perl -pi -e "s/#CC3333/${COLOR_MEDIUM_GRAY^^}/g;" -e "s/#005577/${COLOR_GREEN^^}/g;" /usr/bin/slock
EOF

sudo sed -i "s/kpdl(comma)/kpdl(dot)/g" /usr/share/X11/xkb/symbols/de
sudo tee /etc/pacman.d/hooks/30-xkeyboard-config.hook <<-EOF
	[Trigger]
	Type = Package
	Operation = Upgrade
	Target = xkeyboard-config

	[Action]
	When = PostTransaction
	Exec = /usr/bin/sed -i "s/kpdl(comma)/kpdl(dot)/g" /usr/share/X11/xkb/symbols/de
EOF

sudo systemctl enable ufw.service
sudo ufw default reject incoming
sudo ufw default allow outgoing
sudo ufw allow proto tcp to 0.0.0.0/0 port 22
sudo ufw enable

sudo tee /etc/ssh/ssh_config <<-EOF
	SendEnv LANG LC_*
	ServerAliveInterval 10
	StrictHostKeyChecking yes
EOF
sudo tee /etc/ssh/sshd_config <<-EOF
	Port 22

	AcceptEnv LANG LC_*
	AddressFamily inet
	AllowUsers ${USER}
	AuthenticationMethods publickey
	ClientAliveInterval 10
	LoginGraceTime 10
	Subsystem sftp /usr/lib/ssh/sftp-server
EOF
sudo systemctl enable sshd.service

sudo tee /etc/X11/xorg.conf.d/10-keyboard.conf <<-EOF
	Section "InputClass"
	        Identifier "Keyboard configuration"
	        MatchIsKeyboard "on"
	        Option "XkbLayout" "de"
	        Option "XkbVariant" "nodeadkeys"
	EndSection
EOF
sudo tee /etc/X11/xorg.conf.d/90-default.conf <<-EOF
	Section "ServerFlags"
	    Option "DontVTSwitch"
	    Option "DontZap"
	EndSection

	Section "ServerLayout"
	    Identifier "Display control"
	    Option "StandbyTime" "0"
	    Option "SuspendTime" "0"
	    Option "OffTime" "10"
	    Option "BlankTime" "5"
	EndSection
EOF

sudo mkdir -p /usr/share/icons/default
sudo tee /usr/share/icons/default/index.theme <<-EOF
	[Icon Theme]
	Inherits=Vanilla-DMZ
EOF

sudo mkdir -p /etc/gtk-2.0
sudo tee /etc/gtk-2.0/gtkrc <<-EOF
	gtk-theme-name = "Arc-Lighter"
	gtk-icon-theme-name = "Arc"
	gtk-cursor-theme-name = "Vanilla-DMZ"
	gtk-font-name = "Source Sans Pro 12"
	gtk-button-images = 1
	gtk-cursor-theme-size = 0
	gtk-enable-event-sounds = 1
	gtk-enable-input-feedback-sounds = 1
	gtk-menu-images = 1
	gtk-toolbar-icon-size = GTK_ICON_SIZE_LARGE_TOOLBAR
	gtk-toolbar-style = GTK_TOOLBAR_BOTH
	gtk-xft-antialias = 1
	gtk-xft-hinting = 1
	gtk-xft-hintstyle = "hintfull"
	gtk-xft-rgba = "rgb"
EOF

sudo mkdir -p /etc/gtk-3.0
sudo tee /etc/gtk-3.0/settings.ini <<-EOF
	[Settings]
	gtk-theme-name = Arc-Lighter
	gtk-icon-theme-name = Arc
	gtk-cursor-theme-name = Vanilla-DMZ
	gtk-font-name = Source Sans Pro 12
	gtk-button-images = 1
	gtk-cursor-theme-size = 0
	gtk-decoration-layout = menu:
	gtk-enable-event-sounds = 1
	gtk-enable-input-feedback-sounds = 1
	gtk-menu-images = 1
	gtk-toolbar-icon-size = GTK_ICON_SIZE_LARGE_TOOLBAR
	gtk-toolbar-style = GTK_TOOLBAR_BOTH
	gtk-xft-antialias = 1
	gtk-xft-hinting = 1
	gtk-xft-hintstyle = hintfull
	gtk-xft-rgba = rgb
EOF

sudo mkdir -p /etc/xdg
sudo tee /etc/xdg/mimeapps.list <<-EOF
	[Default Applications]
	application/javascript=sublime_text.desktop
	application/json=sublime_text.desktop
	application/sql=sublime_text.desktop
	application/xml=sublime_text.desktop
	application/x-shellscript=sublime_text.desktop
	image/bmp=gpicview.desktop
	image/gif=gpicview.desktop
	image/jpeg=gpicview.desktop
	image/png=gpicview.desktop
	image/tiff=gpicview.desktop
	image/svg+xml=gpicview.desktop
	text/css=sublime_text.desktop
	text/csv=sublime_text.desktop
	text/html=sublime_text.desktop
	text/markdown=sublime_text.desktop
	text/plain=sublime_text.desktop
	text/x-c=sublime_text.desktop
	text/x-c++=sublime_text.desktop
	text/x-java=sublime_text.desktop
EOF

mkdir -p "${HOME}/.local/bin"
tee "${HOME}/.local/bin/application-launcher" <<-EOF
	#!/bin/bash

	declare -A BUFFER
	while IFS="=" read -r APPLICATION EXECUTABLE
	    do
	        BUFFER+=(["\${APPLICATION}"]="\${EXECUTABLE}")
	    done < "\${HOME}/.config/application-launcher/config"
	while IFS="=" read -r APPLICATION EXECUTABLE
	    do
	        BUFFER+=(["\${APPLICATION}"]="\${EXECUTABLE}")
	    done <<< "\$(flatpak list --app | awk 'BEGIN { FS="\t" } { printf "%s=/usr/bin/flatpak run %s\n", tolower(\$1), \$2 }')"

	SELECTION="\$(dmenu -i -sb "#6f6f6f" <<< \$(printf "%s\n" "\${!BUFFER[@]}" | sort))"
	if [[ -n "\${SELECTION}" ]]
	    then
	        i3-msg "exec --no-startup-id \${BUFFER[\${SELECTION}]}"
	fi
EOF
chmod +x "${HOME}/.local/bin/application-launcher"

tee "${HOME}/.local/bin/display-configuration" <<-EOF
	#!/bin/bash

	for MONITOR in "\$(xrandr | awk '\$2 == "connected" { print \$1 }')"
	    do
	        xrandr --output "\${MONITOR}" --auto
	    done

	if [[ -d "\${HOME}/.local/share/backgrounds" ]]
	    then
	        feh --bg-fill --no-fehbg --randomize "\${HOME}/.local/share/backgrounds"
	    else
	        xsetroot -grey
	fi
EOF
chmod +x "${HOME}/.local/bin/display-configuration"

tee "${HOME}/.local/bin/screenshot" <<-EOF
	#!/bin/bash

	FILE="%Y-%m-%d-%H-%M-%S.png"
	ARGS=("--overwrite")
	while [[ "\${#}" > 0 ]]
	    do
	        case "\${1}" in
	            -s|--select)
	                ARGS+=("--select")
	                shift
	                ;;
	            -c|--clipboard)
	                FILE="\$(mktemp --suffix=".png")"
	                trap "{ xclip -selection clipboard -target image/png -in \${FILE}; rm -rf \${FILE}; }" EXIT
	                shift
	                ;;
	        esac
	    done
	scrot "\${ARGS[@]}" "\${FILE}"
EOF
chmod +x "${HOME}/.local/bin/screenshot"

mkdir -p "${HOME}/.config/application-launcher"
tee "${HOME}/.config/application-launcher/config" <<-EOF
	alacritty=/usr/bin/alacritty
	firefox=/usr/bin/firefox
	gimp=/usr/bin/gimp
	gpicview=/usr/bin/gpicview
	libreoffice=/usr/bin/libreoffice
	pavucontrol=/usr/bin/pavucontrol
	pcmanfm=/usr/bin/pcmanfm
	sublime-text=/usr/bin/subl
	thunderbird=/usr/bin/thunderbird
EOF

tee "${HOME}/.xinitrc" <<-EOF
	dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY
	xrdb -merge "\${HOME}/.Xresources"
	mkdir -p "/run/user/\${UID}/i3"
	mkdir -p "/run/user/\${UID}/i3status"
	awk 'NR!=1 && FNR==1 { printf "\n" } { print }' "\${HOME}/.config/i3.d/"* > "/run/user/\${UID}/i3/config"
	awk 'NR!=1 && FNR==1 { printf "\n" } { print }' "\${HOME}/.config/i3status.d/"* > "/run/user/\${UID}/i3status/config"
	exec /usr/bin/i3 -c "/run/user/\${UID}/i3/config"  > /dev/null 2>&1
EOF

tee "${HOME}/.Xresources" <<-EOF
	Xft.dpi: 96
	XTerm.termName: xterm
	XTerm.title: Terminal
	XTerm.VT100.faceName: Source Code Pro
	XTerm.VT100.faceSize: 14
	XTerm.VT100.allowBoldFonts: false
	XTerm.VT100.background: rgb:28/28/28
	XTerm.VT100.foreground: rgb:f7/f7/f7
	XTerm.VT100.color0: rgb:6f/6f/6f
	XTerm.VT100.color1: rgb:f9/24/72
	XTerm.VT100.color2: rgb:a6/e2/2c
	XTerm.VT100.color3: rgb:e7/db/74
	XTerm.VT100.color4: rgb:67/d8/ef
	XTerm.VT100.color5: rgb:ac/80/ff
	XTerm.VT100.color6: rgb:2a/a1/98
	XTerm.VT100.color7: rgb:f8/f8/f8
	XTerm.VT100.color8: rgb:28/28/28
	XTerm.VT100.color9: rgb:f9/24/72
	XTerm.VT100.color10: rgb:a6/e2/2c
	XTerm.VT100.color11: rgb:e7/db/74
	XTerm.VT100.color12: rgb:67/d8/ef
	XTerm.VT100.color13: rgb:ac/80/ff
	XTerm.VT100.color14: rgb:2a/a1/98
	XTerm.VT100.color15: rgb:f7/f7/f7
	XTerm.VT100.alternateScroll: true
	XTerm.VT100.fastScroll: true
	XTerm.VT100.jumpScroll: true
	XTerm.VT100.multiScroll: true
	XTerm.VT100.on2Clicks: regex (https?:)?[a-zA-Z0-9$%&/()?@~*+#,._-]+
	XTerm.VT100.on3Clicks: line
	XTerm.VT100.saveLines: 16384
	XTerm.VT100.translations: #override \n\\
	    Shift Ctrl <Key> c: copy-selection(CLIPBOARD) \n\\
	    Shift Ctrl <Key> v: insert-selection(CLIPBOARD)
EOF

tee "${HOME}/.bash_profile" <<-EOF
	umask g-rwx,o-rwx
	if [[ -n "\${BASH_VERSION}" && -f "\${HOME}/.bashrc" ]]
	    then
	        source "\${HOME}/.bashrc"
	fi
	if [[ -d "\${HOME}/.local/bin" ]]
	    then
	        PATH="\${HOME}/.local/bin:\${PATH}"
	fi
	if [[ ! "\${DISPLAY}" && "\${XDG_VTNR}" -eq 1 ]]
	    then
	        exec startx
	fi
EOF

tee "${HOME}/.bashrc" <<-EOF
	case \$- in
	    *i*)
	        if [[ -z "\${SSH_CLIENT:+SUBSTITUTION}" ]]
	            then
	                PS1="\[\e[32m\]\u@\h\[\e[m\]:\[\e[34m\]\w\[\e[m\]\\$ "
	            else
	                PS1="\[\e[31m\]\u@\h\[\e[m\]:\[\e[34m\]\w\[\e[m\]\\$ "
	        fi

	        export EDITOR="vim"
	        export PAGER="less"
	        export SYSTEMD_PAGER="less"

	        HISTCONTROL="ignoreboth"
	        HISTFILESIZE="-1"
	        HISTSIZE="-1"
	        HISTTIMEFORMAT="%Y-%m-%d %H:%M:%S "

	        function history:disable () {
	            echo -e "\e[93mDISABLE BASH HISTORY\e[0m"
	            unset HISTFILE
	        }
	        bind -x '"\eh":"history:disable"'

	        shopt -s autocd
	        shopt -s checkwinsize
	        shopt -s globstar
	        shopt -s histappend
	        tabs 4

	        eval \$(dircolors -b)

	        function ssh-agent:init () {
	            pgrep -u "\${USER}" ssh-agent
	            if [[ "\${?}" -ne 0 ]]
	                then
	                    ssh-agent -s > "\${HOME}/.sshrc"
	                    source "\${HOME}/.sshrc"
	                    ssh-add "\${HOME}/.ssh/id_rsa"
	                else
	                    source "\${HOME}/.sshrc"
	            fi
	        }
	        ssh-agent:init > /dev/null

	        alias diff="/usr/bin/diff --color=auto"
	        alias grep="/usr/bin/grep --color=auto"
	        alias ip="/usr/bin/ip -color=auto"
	        alias less="/usr/bin/less --ignore-case"
	        alias ls="/usr/bin/ls --color=auto --group-directories-first"

	        alias bc="/usr/bin/bc --mathlib"
	        alias cal="/usr/bin/cal --months 9 --span"

	        for COMMAND in poweroff reboot suspend hibernate
	            do
	                alias "\${COMMAND}"="/usr/bin/systemctl \${COMMAND}"
	            done

	        function git:pretty () {
	            PARAMETERS=("\${@}")
	            case "\${1}" in
	                log)
	                    /usr/bin/git --no-pager log --reverse "\${PARAMETERS[@]:1}"
	                    ;;
	                graph)
	                    /usr/bin/git --no-pager log --color=always --graph "\${PARAMETERS[@]:1}" | less -r
	                    ;;
	                *)
	                    /usr/bin/git --no-pager "\${PARAMETERS[@]}"
	                    ;;
	            esac
	        }
	        alias git="git:pretty"

	        if [[ -f "\${HOME}/.bash_aliases" ]]
	            then
	                source "\${HOME}/.bash_aliases"
	        fi

	        if [[ -d "\${HOME}/.bash/" ]]
	            then
	                for FILE in \$(find "\${HOME}/.bash/" -maxdepth 1 -type f -executable)
	                do
	                    alias "\$(basename "\${FILE}")"="\${FILE}"
	                done
	        fi
	        ;;
	esac
EOF

tee "${HOME}/.bash_logout" <<-EOF
EOF

tee "${HOME}/.hushlogin" <<-EOF
EOF

mkdir -p "${HOME}/.config/i3.d"
tee "${HOME}/.config/i3.d/10-default" <<-EOF
	set \$mod Mod4
	floating_modifier \$mod

	font pango:Source Code Pro 10
	client.focused ${COLOR_DARK_GRAY} ${COLOR_DARK_GRAY} ${COLOR_WHITE} ${COLOR_MEDIUM_GRAY}
	client.focused_inactive ${COLOR_DARK_GRAY} ${COLOR_DARK_GRAY} ${COLOR_MEDIUM_GRAY} ${COLOR_WHITE}
	client.unfocused ${COLOR_DARK_GRAY} ${COLOR_DARK_GRAY} ${COLOR_MEDIUM_GRAY} ${COLOR_WHITE}
	client.urgent ${COLOR_DARK_GRAY} ${COLOR_PINK} ${COLOR_WHITE} ${COLOR_PINK}

	bindsym \$mod+Return exec --no-startup-id alacritty
	bindsym \$mod+Shift+q kill
	bindsym \$mod+d exec --no-startup-id application-launcher

	bindsym \$mod+Left focus left
	bindsym \$mod+Down focus down
	bindsym \$mod+Up focus up
	bindsym \$mod+Right focus right
	bindsym \$mod+Shift+Left move left
	bindsym \$mod+Shift+Down move down
	bindsym \$mod+Shift+Up move up
	bindsym \$mod+Shift+Right move right
	bindsym \$mod+Shift+n move workspace to output left
	bindsym \$mod+Shift+m move workspace to output right

	bindsym \$mod+h split h
	bindsym \$mod+v split v
	bindsym \$mod+f fullscreen
	bindsym \$mod+s layout stacking
	bindsym \$mod+w layout tabbed
	bindsym \$mod+e layout toggle split
	bindsym \$mod+Shift+space floating toggle
	bindsym \$mod+space focus mode_toggle
	bindsym \$mod+a focus parent
	bindsym \$mod+c focus child

	bindsym \$mod+1 workspace 1
	bindsym \$mod+2 workspace 2
	bindsym \$mod+3 workspace 3
	bindsym \$mod+4 workspace 4
	bindsym \$mod+5 workspace 5
	bindsym \$mod+6 workspace 6
	bindsym \$mod+7 workspace 7
	bindsym \$mod+8 workspace 8
	bindsym \$mod+9 workspace 9
	bindsym \$mod+0 workspace 10:X
	bindsym \$mod+F1 workspace 11:F1
	bindsym \$mod+F2 workspace 12:F2
	bindsym \$mod+F3 workspace 13:F3
	bindsym \$mod+F4 workspace 14:F4
	bindsym \$mod+F5 workspace 15:F5
	bindsym \$mod+F6 workspace 16:F6
	bindsym \$mod+F7 workspace 17:F7
	bindsym \$mod+F8 workspace 18:F8
	bindsym \$mod+F9 workspace 19:F9
	bindsym \$mod+F10 workspace 20:F10
	bindsym \$mod+F11 workspace 21:F11
	bindsym \$mod+F12 workspace 22:F12
	bindsym \$mod+Shift+1 move container to workspace 1
	bindsym \$mod+Shift+2 move container to workspace 2
	bindsym \$mod+Shift+3 move container to workspace 3
	bindsym \$mod+Shift+4 move container to workspace 4
	bindsym \$mod+Shift+5 move container to workspace 5
	bindsym \$mod+Shift+6 move container to workspace 6
	bindsym \$mod+Shift+7 move container to workspace 7
	bindsym \$mod+Shift+8 move container to workspace 8
	bindsym \$mod+Shift+9 move container to workspace 9
	bindsym \$mod+Shift+0 move container to workspace 10:X
	bindsym \$mod+Shift+F1 move container to workspace 11:F1
	bindsym \$mod+Shift+F2 move container to workspace 12:F2
	bindsym \$mod+Shift+F3 move container to workspace 13:F3
	bindsym \$mod+Shift+F4 move container to workspace 14:F4
	bindsym \$mod+Shift+F5 move container to workspace 15:F5
	bindsym \$mod+Shift+F6 move container to workspace 16:F6
	bindsym \$mod+Shift+F7 move container to workspace 17:F7
	bindsym \$mod+Shift+F8 move container to workspace 18:F8
	bindsym \$mod+Shift+F9 move container to workspace 19:F9
	bindsym \$mod+Shift+F10 move container to workspace 20:F10
	bindsym \$mod+Shift+F11 move container to workspace 21:F11
	bindsym \$mod+Shift+F12 move container to workspace 22:F12

	set \$exit i3 [e]xit [r]estart
	bindsym \$mod+Shift+e mode "\$exit"
	mode "\$exit" {
	    bindsym e exec i3-msg exit; mode default
	    bindsym r exec i3-msg restart; mode default
	    bindsym Escape mode default
	}

	set \$resize Resize
	bindsym \$mod+r mode "\$resize"
	mode "\$resize" {
	    bindsym Left resize shrink width 10 px or 10 ppt
	    bindsym Down resize grow height 10 px or 10 ppt
	    bindsym Up resize shrink height 10 px or 10 ppt
	    bindsym Right resize grow width 10 px or 10 ppt
	    bindsym Return mode default
	    bindsym Escape mode default
	}
EOF
tee "${HOME}/.config/i3.d/20-display" <<-EOF
	exec --no-startup-id display-configuration
	bindsym \$mod+Shift+d exec --no-startup-id display-configuration
EOF
tee "${HOME}/.config/i3.d/30-status" <<-EOF
	bar {
	    status_command i3status -c "/run/user/\${UID}/i3status/config"
	    position bottom
	    strip_workspace_numbers yes

	    colors {
	        background ${COLOR_DARK_GRAY}
	        statusline ${COLOR_WHITE}
	        separator ${COLOR_MEDIUM_GRAY}
	        focused_workspace ${COLOR_WHITE} ${COLOR_MEDIUM_GRAY} ${COLOR_WHITE}
	        active_workspace ${COLOR_WHITE} ${COLOR_MEDIUM_GRAY} ${COLOR_WHITE}
	        inactive_workspace ${COLOR_MEDIUM_GRAY} ${COLOR_DARK_GRAY} ${COLOR_WHITE}
	        urgent_workspace ${COLOR_MEDIUM_GRAY} ${COLOR_PINK} ${COLOR_WHITE}
	    }
	}
EOF
tee "${HOME}/.config/i3.d/40-volume" <<-EOF
	bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -1%
	bindsym \$mod+minus exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -1%
	bindsym \$mod+Shift+minus exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10%
	bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +1%
	bindsym \$mod+plus exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +1%
	bindsym \$mod+Shift+plus exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10%
	bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle
	bindsym \$mod+numbersign exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle
	exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ 95%
	exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ 1
EOF
tee "${HOME}/.config/i3.d/60-slock" <<-EOF
	exec --no-startup-id xss-lock slock
	bindsym --release \$mod+l exec --no-startup-id loginctl lock-session
EOF
tee "${HOME}/.config/i3.d/61-numlockx" <<-EOF
	exec --no-startup-id numlockx on
EOF
tee "${HOME}/.config/i3.d/62-screenshot" <<-EOF
	bindsym Print exec --no-startup-id screenshot
	bindsym --release Shift+Print exec --no-startup-id screenshot --select --clipboard
EOF
tee "${HOME}/.config/i3.d/63-dunst" <<-EOF
	exec --no-startup-id dunst
	bindsym \$mod+j exec --no-startup-id dunstctl history-pop
EOF

mkdir -p "${HOME}/.config/i3status.d"
tee "${HOME}/.config/i3status.d/10-default" <<-EOF
	general {
	    colors = true
	    color_good = "${COLOR_GREEN}"
	    color_degraded = "${COLOR_MEDIUM_GRAY}"
	    color_bad = "${COLOR_PINK}"
	    interval = 5
	}
EOF
tee "${HOME}/.config/i3status.d/20-volume" <<-EOF
	order += "volume pulse"
	volume pulse {
	    format = "🔊 %volume"
	    format_muted = "🔈"
	    device = "pulse"
	}
EOF
tee "${HOME}/.config/i3status.d/30-disk" <<-EOF
	order += "disk /"
	disk / {
	    format = "%free"
	}
EOF
NIC="$(ip --brief link show | awk '$2 == "UP" { print $1; exit }')"
if [[ "${NIC}" = w* ]]
	then
		tee "${HOME}/.config/i3status.d/60-wlan" <<-EOF
			order += "wireless ${NIC}"
			wireless ${NIC} {
			    format_up = "%essid"
			    format_down = "🖧"
			}
		EOF
	else
		tee "${HOME}/.config/i3status.d/70-ethernet" <<-EOF
			order += "ethernet ${NIC}"
			ethernet ${NIC} {
			    format_up = "%ip"
			    format_down = "🖧"
			}
		EOF
fi
tee "${HOME}/.config/i3status.d/90-time" <<-EOF
	order += "tztime local"
	tztime local {
	    format = "%Y-%m-%d %H:%M"
	}
EOF

mkdir -p "${HOME}/.config/dunst"
tee "${HOME}/.config/dunst/dunstrc" <<-EOF
	[global]
	    geometry="300x1-10-35"
	    padding = 10
	    horizontal_padding = 10
	    frame_width = 1
	    font = "Source Code Pro 10"
	    line_height = 3
	    format = "<b>%s</b>\n%b"
	    word_wrap = true
	    hide_duplicate_count = true
	    show_indicators = false

	[urgency_low]
	    background = "${COLOR_DARK_GRAY}"
	    foreground = "${COLOR_WHITE}"
	    frame_color = "${COLOR_MEDIUM_GRAY}"
	    timeout = 3

	[urgency_normal]
	    background = "${COLOR_DARK_GRAY}"
	    foreground = "${COLOR_WHITE}"
	    frame_color = "${COLOR_MEDIUM_GRAY}"
	    timeout = 10

	[urgency_critical]
	    background = "${COLOR_DARK_GRAY}"
	    foreground = "${COLOR_WHITE}"
	    frame_color = "${COLOR_MEDIUM_GRAY}"
	    timeout = 0
EOF

mkdir -p "${HOME}/.config/alacritty"
tee "${HOME}/.config/alacritty/alacritty.yml" <<-EOF
	env:
	  TERM: xterm

	window:
	  decorations: full
	  title: Terminal
	  dynamic_title: true
	  class:
	    instance: Terminal
	    general: Auf zum Atem!

	colors:
	  primary:
	    background: '#282828'
	    foreground: '#f7f7f7'
	  normal:
	    black:   '#6f6f6f'
	    red:     '#f92472'
	    green:   '#a6e22c'
	    yellow:  '#e7db74'
	    blue:    '#67d8ef'
	    magenta: '#ac80ff'
	    cyan:    '#2aa198'
	    white:   '#f8f8f8'
	  bright:
	    black:   '#282828'
	    red:     '#f92472'
	    green:   '#a6e22c'
	    yellow:  '#e7db74'
	    blue:    '#67d8ef'
	    magenta: '#ac80ff'
	    cyan:    '#2aa198'
	    white:   '#f7f7f7'
	  selection:
	   text: '#282828'
	   background: '#f7f7f7'
	  line_indicator:
	    foreground: '#282828'
	    background: '#f7f7f7'
	  search:
	    matches:
	      foreground: '#282828'
	      background: '#f7f7f7'
	    focused_match:
	      foreground: '#f7f7f7'
	      background: '#2aa198'
	    bar:
	      foreground: '#282828'
	      background: '#f7f7f7'
	  hints:
	    start:
	      foreground: '#f7f7f7'
	      background: '#f92472'
	    end:
	      foreground: '#f92472'
	      background: '#f7f7f7'
	background_opacity: 1.0

	font:
	  normal:
	    family: Source Code Pro
	    style: Regular
	  bold:
	    style: Regular
	  italic:
	    style: Regular
	  bold_italic:
	    style: Regular
	  size: 14.0
	draw_bold_text_with_bright_colors: false

	cursor:
	  style:
	    shape: Block
	    blinking: Always
	  blink_interval: 750
	  unfocused_hollow: true

	scrolling:
	  history: 16384
	  multiplier: 4

	mouse:
	  double_click:
	    threshold: 400
	  triple_click:
	    threshold: 400
	  hide_when_typing: false

	selection:
	  semantic_escape_chars: ",│\`|:\"' ()[]{}<>\t"
	  save_to_clipboard: false

	bell:
	  animation: Linear
	  duration: 0
	  color: '#f7f7f7'

	alt_send_esc: true

	shell:
	  program: /bin/bash
	  args: [ '--login' ]
	working_directory: None

	hints:
	  enabled:
	    - regex: "(https?://)[a-zA-Z0-9\$%&/()?@~*+#,._-]+"
	      action: Copy
	      post_processing: true
	      mouse:
	        enabled: true
	        mods: None
	      binding:
	        key: U
	        mods: Control|Shift

	live_config_reload: false
EOF

mkdir -p "${HOME}/.config/pcmanfm/default"
tee "${HOME}/.config/pcmanfm/default/pcmanfm.conf" <<-EOF
	[volume]
	autorun=0
	mount_on_startup=0
	mount_removable=0

	[ui]
	view_mode=compact
EOF
mkdir -p "${HOME}/.config/libfm"
tee "${HOME}/.config/libfm/libfm.conf" <<-EOF
	[config]
	terminal=alacritty

	[places]
	places_applications=0
	places_computer=0
	places_desktop=0
	places_home=1
	places_network=0
	places_root=1
	places_trash=1
	places_unmounted=1
EOF

mkdir -p "${HOME}/.config/sublime-text-3/Packages/User"
unzip -p "/opt/sublime_text/Packages/Color Scheme - Default.sublime-package" Monokai.sublime-color-scheme \
| sed -r "s/\"(name)\"(\s*):(\s*)\"Monokai\"/\"\1\"\2:\3\"Auf zum Atem\!\"/g" \
| sed -r "s/\"(author)\"(\s*):(\s*)\".*?\"/\"\1\"\2:\3\"Me\"/g" \
| sed -r "s/\"(black2)\"(\s*):(\s*)\"hsl\(.*?\)\"/\"\1\"\2:\3\"rgb(32, 32, 32)\"/g" \
| sed -r "s/\"(black3)\"(\s*):(\s*)\"hsl\(.*?\)\"/\"\1\"\2:\3\"rgb(40, 40, 40)\"/g" \
| sed -r "s/\"(grey)\"(\s*):(\s*)\"hsl\(.*?\)\"/\"\1\"\2:\3\"rgb(70, 70, 70)\"/g" \
| sed -r "s/\"(white)\"(\s*):(\s*)\"hsl\(.*?\)\"/\"\1\"\2:\3\"rgb(247, 247, 247)\"/g" \
| sed -r "s/\"(white2)\"(\s*):(\s*)\"hsl\(.*?\)\"/\"\1\"\2:\3\"rgb(248, 248, 248)\"/g" \
| sed -r "s/\"(white3)\"(\s*):(\s*)\"hsl\(.*?\)\"/\"\1\"\2:\3\"rgb(247, 247, 247)\"/g" \
| sed -r "s/\"(yellow3)\"(\s*):(\s*)\"hsl\(.*?\)\"/\"\1\"\2:\3\"rgb(206, 206, 206)\"/g" \
| sed -r "s/\"(yellow4)\"(\s*):(\s*)\"hsl\(.*?\)\"/\"\1\"\2:\3\"rgb(60, 60, 60)\"/g" \
| sed -r "s/\"(yellow5)\"(\s*):(\s*)\"hsl\(.*?\)\"/\"\1\"\2:\3\"rgb(111, 111, 111)\"/g" \
| tee "${HOME}/.config/sublime-text-3/Packages/User/Auf zum Atem"'!'".sublime-color-scheme"
tee "${HOME}/.config/sublime-text-3/Packages/User/Preferences.sublime-settings" <<-EOF
	{
	    "color_scheme": "Packages/User/Auf zum Atem!.sublime-color-scheme",
	    "draw_white_space": "all",
	    "ensure_newline_at_eof_on_save": true,
	    "fallback_encoding": "ISO 8859-1",
	    "font_face": "Source Code Pro",
	    "font_size": 14,
	    "highlight_line": true,
	    "highlight_modified_tabs": true,
	    "hot_exit": false,
	    "line_padding_bottom": 3,
	    "line_padding_top": 3,
	    "remember_workspace": false,
	    "scroll_speed": 0,
	    "show_encoding": true,
	    "show_line_endings": true,
	    "trim_trailing_white_space_on_save": true
	}
EOF
tee "${HOME}/.config/sublime-text-3/Packages/User/Default (Linux).sublime-keymap" <<-EOF
	[
	    { "keys": ["ctrl+7"], "command": "toggle_comment", "args": { "block": false } },
	    { "keys": ["ctrl+shift+7"], "command": "toggle_comment", "args": { "block": true } }
	]
EOF
mkdir -p "${HOME}/.config/sublime-text-3/Local"
tee "${HOME}/.config/sublime-text-3/Local/Session.sublime_session" <<-EOF
	{"windows":[{"menu_visible": false}]}
EOF

chmod -R go= "${HOME}/"

if [[ "$(</sys/devices/virtual/dmi/id/sys_vendor)" = QEMU ]]
	then
		sudo pacman --noconfirm -S spice-vdagent
		tee "${HOME}/.config/i3.d/21-spice" <<-EOF
			exec --no-startup-id spice-vdagent
		EOF
fi
