#!/bin/bash

set -x

NIC="$(grep -oP "(?<=Name=).*" $(find /etc/systemd/network -type f | sort | head -1))"

sudo sed -i s/"#Color"/"Color"/g /etc/pacman.conf
sudo pacman -Syy
PACKAGES=(
	adobe-source-code-pro-fonts
	adobe-source-sans-pro-fonts
	adobe-source-serif-pro-fonts
	arc-gtk-theme
	arc-icon-theme
	bash-completion
	bc
	bind-tools
	dmenu
	dmidecode
	dunst
	feh
	firefox
	gimp
	git
	gpicview
	gvfs
	htop
	i3-wm
	i3status
	jq
	libnotify
	libreoffice-fresh
	lsof
	man
	mkvtoolnix-cli
	mpv
	nmap
	numlockx
	openssh
	p7zip
	pass
	pavucontrol
	pcmanfm
	polkit
	pulseaudio
	pwgen
	python
	python-virtualenv
	rsync
	scrot
	slock
	sshfs
	tcpdump
	testdisk
	thunderbird
	ttf-liberation
	ufw
	unrar
	unzip
	virt-manager
	wget
	wireshark-qt
	xclip
	xcursor-vanilla-dmz
	xorg-server
	xorg-xinit
	xorg-xrandr
	xorg-xsetroot
	xss-lock
	xterm
	zip
)
sudo pacman -S --noconfirm ${PACKAGES[*]}

SYMBOLA_VERSION="2.60-1"
wget "http://mirrors.kernel.org/ubuntu/pool/universe/t/ttf-ancient-fonts/fonts-symbola_${SYMBOLA_VERSION}_all.deb" -O /tmp/fonts-symbola.deb
7z x -so /tmp/fonts-symbola.deb data.tar | tar -xO ./usr/share/fonts/truetype/ancient-scripts/Symbola_hint.ttf > /tmp/Symbola.ttf
sudo mkdir -p /usr/share/fonts/truetype/ancient-scripts
sudo cp /tmp/Symbola.ttf /usr/share/fonts/truetype/ancient-scripts

SUBLIME_VERSION="3211"
wget "https://download.sublimetext.com/sublime_text_3_build_${SUBLIME_VERSION}_x64.tar.bz2" -O "/tmp/sublime_text_3_build_${SUBLIME_VERSION}_x64.tar.bz2"
sudo tar -jxvf "/tmp/sublime_text_3_build_${SUBLIME_VERSION}_x64.tar.bz2" -C /opt
sudo ln -s /opt/sublime_text_3/sublime_text /usr/local/bin/sublime-text

sudo tee /usr/local/bin/archiver <<-EOF
	#!/bin/bash

	[[ "\${#}" -eq 1 && -f "\${1}" ]] || exit 1
	FILENAME="\${1}"
	MIME_TYPE="\$(file --brief --mime-type "\${FILENAME}")"
	case "\${MIME_TYPE}" in
	    "application/zip")
	        xterm -e "unzip -l \"\${FILENAME}\" | less"
	        ;;
	    "application/gzip")
	        xterm -e "gzip -d -c \"\${FILENAME}\" | less"
	        ;;
	    "application/x-bzip")
	        xterm -e "bzip2 -d -c \"\${FILENAME}\" | less"
	        ;;
	    "application/x-lzma")
	        xterm -e "lzma -d -c \"\${FILENAME}\" | less"
	        ;;
	    "application/x-xz")
	        xterm -e "xz -d -c \"\${FILENAME}\" | less"
	        ;;
	    "application/x-tar"|"application/x-compressed-tar"|"application/x-bzip-compressed-tar"|"application/x-lzma-compressed-tar"|"application/x-xz-compressed-tar")
	        xterm -e "tar tf \"\${FILENAME}\" | less"
	        ;;
	    "application/x-7z-compressed")
	        xterm -e "7z l \"\${FILENAME}\" | less"
	        ;;
	    "application/x-rar")
	        xterm -e "unrar l \"\${FILENAME}\" | less"
	        ;;
	    *)
	        xterm -e "echo \"Unsupported MIME type: \${MIME_TYPE}\" | less"
	        ;;
	esac
EOF
sudo chmod +x /usr/local/bin/archiver

sudo tee /usr/local/bin/mpv <<-EOF
	#!/bin/bash

	MPV="/usr/bin/mpv"
	if [[ -t 1 ]]
	    then
	        "\${MPV}" "\${@}"
	    else
	        [[ "\${#}" -eq 1 && -f "\${1}" ]] || exit 1
	        FILENAME="\${1}"
	        MIME_TYPE="\$(file --brief --mime-type "\${FILENAME}")"
	        case "\${MIME_TYPE}" in
	            "video/x-matroska")
	                "\${MPV}" "\${FILENAME}"
	                ;;
	            *)
	                xterm -e "echo \"Unsupported MIME type: \${MIME_TYPE}\" | less"
	                ;;
	        esac
	fi
EOF
sudo chmod +x /usr/local/bin/mpv

sudo tee /usr/local/bin/screenshot <<-EOF
	#!/bin/bash

	FILE="%Y-%m-%d-%H-%M-%S.png"
	ARGS=("--overwrite")
	for ARGUMENT in "\${@}"
	    do
	        case "\${ARGUMENT}" in
	            "-s"|"--select")
	                ARGS+=("--select")
	                shift
	                ;;
	            "-c"|"--clipboard")
	                FILE="\$(mktemp --suffix=".png")"
	                trap "{ xclip -selection clipboard -target image/png -in \"\${FILE}\"; rm -rf \"\${FILE}\"; }" EXIT
	                shift
	                ;;
	        esac
	    done
	scrot \${ARGS[*]} "\${FILE}"
EOF
sudo chmod +x /usr/local/bin/screenshot

sudo perl -pi -e "s/#CC3333/#707070/g" /usr/bin/slock
sudo perl -pi -e "s/#005577/#A6E22E/g" /usr/bin/slock

sudo ln -s /usr/bin/vim /usr/local/bin/vi

sudo systemctl mask avahi-daemon.service
sudo systemctl enable ufw.service
sudo ufw default reject incoming
sudo ufw default allow outgoing
sudo ufw allow proto tcp to 0.0.0.0/0 port 22
sudo ufw enable
sudo usermod -a -G wireshark "${USER}"

sudo tee /etc/ssh/ssh_config <<-EOF
	# $(lsb_release -d -s 2> /dev/null)
	# $(date --iso-8601=seconds 2> /dev/null)

	SendEnv LANG LC_*
EOF
sudo tee /etc/ssh/sshd_config <<-EOF
	# $(lsb_release -d -s 2> /dev/null)
	# $(date --iso-8601=seconds 2> /dev/null)

	Port 22

	HostKey /etc/ssh/ssh_host_rsa_key
	HostKeyAlgorithms ssh-rsa

	AcceptEnv LANG LC_*
	AddressFamily inet
	AllowUsers ${USER}
	AuthenticationMethods publickey
	ClientAliveInterval 10
	LoginGraceTime 10
	Subsystem sftp /usr/lib/openssh/sftp-server
EOF
sudo systemctl enable sshd.service

sudo sed -i "s/kpdl(comma)/kpdl(dot)/g" /usr/share/X11/xkb/symbols/de
sudo tee /etc/X11/xorg.conf.d/10-keyboard.conf <<-EOF
	Section "InputClass"
	        Identifier "system-keyboard"
	        MatchIsKeyboard "on"
	        Option "XkbLayout" "de"
	        Option "XkbVariant" "nodeadkeys"
	EndSection
EOF
sudo tee /etc/X11/xorg.conf.d/90-default.conf <<-EOF
	Section "ServerFlags"
	    Option "DontVTSwitch" "true"
	EndSection

	Section "ServerLayout"
	    Identifier "Display off"
	    Option "StandbyTime" "0"
	    Option "SuspendTime" "0"
	    Option "OffTime" "10"
	    Option "BlankTime" "5"
	EndSection
EOF

sudo mkdir -p /etc/gtk-2.0
sudo tee /etc/gtk-2.0/gtkrc <<-EOF
	gtk-theme-name = "Arc-Lighter"
	gtk-icon-theme-name = "Arc"
	gtk-cursor-theme-name = "Vanilla-DMZ"
	gtk-font-name = "Source Sans Pro 12"
	gtk-button-images = 1
	gtk-cursor-theme-size = 0
	gtk-enable-event-sounds = 1
	gtk-enable-input-feedback-sounds = 1
	gtk-menu-images = 1
	gtk-toolbar-icon-size = GTK_ICON_SIZE_LARGE_TOOLBAR
	gtk-toolbar-style = GTK_TOOLBAR_BOTH
	gtk-xft-antialias = 1
	gtk-xft-hinting = 1
	gtk-xft-hintstyle = "hintfull"
	gtk-xft-rgba = "rgb"
EOF
sudo mkdir -p /etc/gtk-3.0
sudo tee /etc/gtk-3.0/settings.ini <<-EOF
	[Settings]
	gtk-theme-name = Arc-Lighter
	gtk-icon-theme-name = Arc
	gtk-cursor-theme-name = Vanilla-DMZ
	gtk-font-name = Source Sans Pro 12
	gtk-button-images = 1
	gtk-cursor-theme-size = 0
	gtk-decoration-layout = menu:
	gtk-enable-event-sounds = 1
	gtk-enable-input-feedback-sounds = 1
	gtk-menu-images = 1
	gtk-toolbar-icon-size = GTK_ICON_SIZE_LARGE_TOOLBAR
	gtk-toolbar-style = GTK_TOOLBAR_BOTH
	gtk-xft-antialias = 1
	gtk-xft-hinting = 1
	gtk-xft-hintstyle = hintfull
	gtk-xft-rgba = rgb
EOF

sudo find /usr/share/applications -type f,l -delete
sudo mkdir /usr/local/share/applications
sudo python3 <<-EOF
	import os

	def write(name, program, argument=None, display=True):
	    with open(f'/usr/local/share/applications/{program}.desktop', mode='w', encoding='utf-8') as fd:
	        lines = list()
	        lines.append(f'[Desktop Entry]')
	        lines.append(f'Version=1.0')
	        lines.append(f'Type=Application')
	        lines.append(f'Name={name}')
	        if argument is None:
	            lines.append(f'Exec={program}')
	        else:
	            lines.append(f'Exec={program} {argument}')
	        if display:
	            lines.append(f'NoDisplay=false')
	        else:
	            lines.append(f'NoDisplay=true')
	        lines.append(f'StartupNotify=false')
	        lines.append(f'Terminal=false')
	        fd.write(os.linesep.join(lines))
	        fd.write(os.linesep)

	write('Archiver', 'archiver', argument='%f', display=False)
	write('GIMP', 'gimp', argument='%F', display=True)
	write('GPicview', 'gpicview', argument='%f', display=True)
	write('LibreOffice', 'libreoffice', argument='%F', display=True)
	write('Mozilla Firefox', 'firefox', argument='%U', display=True)
	write('Mozilla Thunderbird', 'thunderbird', argument=None, display=True)
	write('MPV', 'mpv', argument='%f', display=False)
	write('PCMan File Manager', 'pcmanfm', argument='%f', display=True)
	write('PulseAudio Volume Control', 'pavucontrol', argument=None, display=True)
	write('Sublime Text', 'sublime-text', argument='%F', display=True)
	write('Terminal', 'xterm', argument=None, display=True)
	write('Virtual Machine Manager', 'virt-manager', argument=None, display=True)
	write('Wireshark', 'wireshark', argument='%f', display=True)
EOF
sudo tee /usr/local/share/applications/defaults.list <<-EOF
	[Default Applications]
	x-scheme-handler/http=firefox.desktop
	x-scheme-handler/https=firefox.desktop
	x-scheme-handler/about=firefox.desktop
	x-scheme-handler/unknown=firefox.desktop

	inode/directory=pcmanfm.desktop

	application/json=sublime-text.desktop
	application/sql=sublime-text.desktop
	application/xml=sublime-text.desktop
	text/css=sublime-text.desktop
	text/csv=sublime-text.desktop
	text/html=sublime-text.desktop
	text/markdown=sublime-text.desktop
	text/plain=sublime-text.desktop

	application/pdf=firefox.desktop

	application/vnd.oasis.opendocument.database=libreoffice.desktop
	application/vnd.oasis.opendocument.formula=libreoffice.desktop
	application/vnd.oasis.opendocument.graphics=libreoffice.desktop
	application/vnd.oasis.opendocument.graphics-template=libreoffice.desktop
	application/vnd.oasis.opendocument.presentation=libreoffice.desktop
	application/vnd.oasis.opendocument.presentation-template=libreoffice.desktop
	application/vnd.oasis.opendocument.spreadsheet=libreoffice.desktop
	application/vnd.oasis.opendocument.spreadsheet-template=libreoffice.desktop
	application/vnd.oasis.opendocument.text=libreoffice.desktop
	application/vnd.oasis.opendocument.text-template=libreoffice.desktop
	application/vnd.oasis.opendocument.text-web=libreoffice.desktop
	application/vnd.oasis.opendocument.text-master=libreoffice.desktop

	image/bmp=gpicview.desktop
	image/gif=gpicview.desktop
	image/jpeg=gpicview.desktop
	image/png=gpicview.desktop
	image/svg+xml=gpicview.desktop
	image/tiff=gpicview.desktop

	video/x-matroska=mpv.desktop

	application/zip=archiver.desktop
	application/gzip=archiver.desktop
	application/x-bzip=archiver.desktop
	application/x-lzma=archiver.desktop
	application/x-xz=archiver.desktop
	application/x-tar=archiver.desktop
	application/x-compressed-tar=archiver.desktop
	application/x-bzip-compressed-tar=archiver.desktop
	application/x-lzma-compressed-tar=archiver.desktop
	application/x-xz-compressed-tar=archiver.desktop
	application/x-7z-compressed=archiver.desktop
	application/vnd.rar=archiver.desktop
	application/vnd.debian.binary-package=archiver.desktop
EOF

tee "${HOME}/.xinitrc" <<-EOF
	xrdb -merge "\${HOME}/.Xresources"
	echo "# This file is automatically generated. Do not edit!" > "\${HOME}/.i3/config"
	for FILE in \$(ls "\${HOME}/.i3/config.d")
	    do
	        echo >> "\${HOME}/.i3/config"
	        cat "\${HOME}/.i3/config.d/\${FILE}" >> "\${HOME}/.i3/config"
	    done
	echo "# This file is automatically generated. Do not edit!" > "\${HOME}/.i3/status"
	for FILE in \$(ls "\${HOME}/.i3/status.d")
	    do
	        echo >> "\${HOME}/.i3/status"
	        cat "\${HOME}/.i3/status.d/\${FILE}" >> "\${HOME}/.i3/status"
	    done
	exec /usr/bin/i3 -c "\${HOME}/.i3/config"
EOF

tee "${HOME}/.Xresources" <<-EOF
	XTerm.termName: xterm
	XTerm.title: Terminal
	XTerm.VT100.faceName: Source Code Pro
	XTerm.VT100.faceSize: 14
	XTerm.VT100.allowBoldFonts: false
	XTerm.VT100.background: rgb:27/27/27
	XTerm.VT100.foreground: rgb:F8/F8/F8
	XTerm.VT100.color0: rgb:70/70/70
	XTerm.VT100.color1: rgb:F9/24/72
	XTerm.VT100.color2: rgb:A6/E2/2C
	XTerm.VT100.color3: rgb:E7/DB/74
	XTerm.VT100.color4: rgb:67/D8/EF
	XTerm.VT100.color5: rgb:AC/80/FF
	XTerm.VT100.color6: rgb:2A/A1/98
	XTerm.VT100.color7: rgb:F8/F8/F8
	XTerm.VT100.color8: rgb:27/27/27
	XTerm.VT100.color9: rgb:F9/24/72
	XTerm.VT100.color10: rgb:A6/E2/2C
	XTerm.VT100.color11: rgb:E7/DB/74
	XTerm.VT100.color12: rgb:67/D8/EF
	XTerm.VT100.color13: rgb:AC/80/FF
	XTerm.VT100.color14: rgb:2A/A1/98
	XTerm.VT100.color15: rgb:F8/F8/F8
	XTerm.VT100.alternateScroll: true
	XTerm.VT100.fastScroll: true
	XTerm.VT100.jumpScroll: true
	XTerm.VT100.multiScroll: true
	XTerm.VT100.on2Clicks: regex (https?:)?[a-zA-Z0-9$%&/()?@~*+#,._-]+
	XTerm.VT100.on3Clicks: line
	XTerm.VT100.saveLines: 16384
	XTerm.VT100.translations: #override \n\\
	    Shift Ctrl <Key> c: copy-selection(CLIPBOARD) \n\\
	    Shift Ctrl <Key> v: insert-selection(CLIPBOARD)
EOF

tee "${HOME}/.bash_profile" <<-EOF
	umask g-rwx,o-rwx
	if [[ -n "\${BASH_VERSION}" && -f "\${HOME}/.bashrc" ]]
	    then
	        source "\${HOME}/.bashrc"
	fi
	if [[ -d "\${HOME}/.local/bin" ]]
	    then
	        PATH="\${HOME}/.local/bin:\${PATH}"
	fi
	if [[ ! "\${DISPLAY}" && "\${XDG_VTNR}" -eq 1 ]]
	    then
	        exec startx
	fi
EOF

rm "${HOME}/.bash_logout"

tee "${HOME}/.bashrc" <<-EOF
	case \$- in
	    *i*)
	        if [[ -z "\${SSH_CLIENT+SSH}" ]]
	            then
	                PS1="\[\e[32m\]\u@\h\[\e[m\]:\[\e[34m\]\w\[\e[m\]\\$ "
	            else
	                PS1="\[\e[31m\]\u@\h\[\e[m\]:\[\e[34m\]\w\[\e[m\]\\$ "
	        fi

	        EDITOR=vim

	        HISTCONTROL=ignoreboth
	        HISTFILESIZE=-1
	        HISTSIZE=-1

	        shopt -s autocd
	        shopt -s checkwinsize
	        shopt -s globstar
	        shopt -s histappend

	        source /usr/share/bash-completion/bash_completion

	        eval \$(dircolors -b)

	        function ssh-agent:init () {
	            pgrep -u "\${USER}" ssh-agent
	            if [[ "\${?}" -ne 0 ]]
	                then
	                    ssh-agent -s > "\${HOME}/.sshrc"
	                    source "\${HOME}/.sshrc"
	                    ssh-add "\${HOME}/.ssh/id_rsa"
	                else
	                    source "\${HOME}/.sshrc"
	            fi
	        }
	        ssh-agent:init > /dev/null

	        alias diff="/usr/bin/diff --color=auto"
	        alias grep="/usr/bin/grep --color=auto"
	        alias ip="/usr/bin/ip -color=auto"
	        alias less="/usr/bin/less --ignore-case"
	        alias ls="/usr/bin/ls --color=auto --group-directories-first"

	        alias poweroff="/usr/bin/systemctl poweroff"
	        alias reboot="/usr/bin/systemctl reboot"
	        alias suspend="/usr/bin/systemctl suspend"

	        alias bc="/usr/bin/bc -l"
	        alias cal="/usr/bin/cal -A 4 -B 4"

	        function git:pretty () {
	            PARAMETERS=("\${@}")
	            case "\${1}" in
	                (log)
	                    /usr/bin/git --no-pager log --all --decorate=full --reverse "\${PARAMETERS[@]:1}"
	                    ;;
	                (graph)
	                    /usr/bin/git --no-pager log --all --decorate=full --graph "\${PARAMETERS[@]:1}"
	                    ;;
	                (*)
	                    /usr/bin/git --no-pager "\${PARAMETERS[@]}"
	                    ;;
	            esac
	        }
	        alias git="git:pretty"

	        if [[ -d "\${HOME}/.bash" ]]
	            then
	                source <(find "\${HOME}/.bash" -maxdepth 1 -type f -executable -printf "alias %P='%p'\n")
	        fi
	        ;;
	esac
EOF

touch "${HOME}/.hushlogin"

tee "${HOME}/.vimrc" <<-EOF
	set expandtab
	set ignorecase
	set smartcase
	set shiftwidth=4
	set softtabstop=4
	set tabstop=4
	syntax on
EOF

mkdir -p "${HOME}/.i3"
tee "${HOME}/.i3/display" <<-EOF
	#!/bin/sh

	for MONITOR in "\$(xrandr | grep connected | grep -v disconnected | awk '{ print \$1 }')"
	    do
	        xrandr --output "\${MONITOR}" --auto
	    done
	xsetroot -grey
EOF
chmod +x "${HOME}/.i3/display"

mkdir -p "${HOME}/.i3/config.d"
tee "${HOME}/.i3/config.d/10-default" <<-EOF
	set \$mod Mod4
	floating_modifier \$mod

	font pango:Source Code Pro 10
	client.focused             #444444    #444444    #F8F8F8    #707070
	client.focused_inactive    #444444    #444444    #707070    #F8F8F8
	client.unfocused           #444444    #444444    #707070    #F8F8F8
	client.urgent              #444444    #F92472    #F8F8F8    #F92472

	bindsym \$mod+Return exec --no-startup-id xterm
	bindsym \$mod+Shift+q kill
	bindsym \$mod+d exec --no-startup-id i3-dmenu-desktop --dmenu="dmenu -i -sb #707070" --entry-type=command

	bindsym \$mod+Left focus left
	bindsym \$mod+Down focus down
	bindsym \$mod+Up focus up
	bindsym \$mod+Right focus right
	bindsym \$mod+Shift+Left move left
	bindsym \$mod+Shift+Down move down
	bindsym \$mod+Shift+Up move up
	bindsym \$mod+Shift+Right move right
	bindsym \$mod+Shift+n move workspace to output left
	bindsym \$mod+Shift+m move workspace to output right

	bindsym \$mod+h split h
	bindsym \$mod+v split v
	bindsym \$mod+f fullscreen
	bindsym \$mod+s layout stacking
	bindsym \$mod+w layout tabbed
	bindsym \$mod+e layout toggle split
	bindsym \$mod+Shift+space floating toggle
	bindsym \$mod+space focus mode_toggle
	bindsym \$mod+a focus parent
	bindsym \$mod+c focus child

	bindsym \$mod+1 workspace 1
	bindsym \$mod+2 workspace 2
	bindsym \$mod+3 workspace 3
	bindsym \$mod+4 workspace 4
	bindsym \$mod+5 workspace 5
	bindsym \$mod+6 workspace 6
	bindsym \$mod+7 workspace 7
	bindsym \$mod+8 workspace 8
	bindsym \$mod+9 workspace 9
	bindsym \$mod+0 workspace 10:X
	bindsym \$mod+F1 workspace 11:F1
	bindsym \$mod+F2 workspace 12:F2
	bindsym \$mod+F3 workspace 13:F3
	bindsym \$mod+F4 workspace 14:F4
	bindsym \$mod+F5 workspace 15:F5
	bindsym \$mod+F6 workspace 16:F6
	bindsym \$mod+F7 workspace 17:F7
	bindsym \$mod+F8 workspace 18:F8
	bindsym \$mod+F9 workspace 19:F9
	bindsym \$mod+F10 workspace 20:F10
	bindsym \$mod+F11 workspace 21:F11
	bindsym \$mod+F12 workspace 22:Spotify
	bindsym \$mod+Shift+1 move container to workspace 1
	bindsym \$mod+Shift+2 move container to workspace 2
	bindsym \$mod+Shift+3 move container to workspace 3
	bindsym \$mod+Shift+4 move container to workspace 4
	bindsym \$mod+Shift+5 move container to workspace 5
	bindsym \$mod+Shift+6 move container to workspace 6
	bindsym \$mod+Shift+7 move container to workspace 7
	bindsym \$mod+Shift+8 move container to workspace 8
	bindsym \$mod+Shift+9 move container to workspace 9
	bindsym \$mod+Shift+0 move container to workspace 10:X
	bindsym \$mod+Shift+F1 move container to workspace 11:F1
	bindsym \$mod+Shift+F2 move container to workspace 12:F2
	bindsym \$mod+Shift+F3 move container to workspace 13:F3
	bindsym \$mod+Shift+F4 move container to workspace 14:F4
	bindsym \$mod+Shift+F5 move container to workspace 15:F5
	bindsym \$mod+Shift+F6 move container to workspace 16:F6
	bindsym \$mod+Shift+F7 move container to workspace 17:F7
	bindsym \$mod+Shift+F8 move container to workspace 18:F8
	bindsym \$mod+Shift+F9 move container to workspace 19:F9
	bindsym \$mod+Shift+F10 move container to workspace 20:F10
	bindsym \$mod+Shift+F11 move container to workspace 21:F11
	bindsym \$mod+Shift+F12 move container to workspace 22:Spotify

	set \$exit i3 [e]xit [r]estart
	bindsym \$mod+Shift+e mode "\$exit"
	mode "\$exit" {
	    bindsym e exec i3-msg exit; mode default
	    bindsym r exec i3-msg restart; mode default
	    bindsym Escape mode default
	}

	set \$resize Resize
	bindsym \$mod+r mode "\$resize"
	mode "\$resize" {
	    bindsym Left resize shrink width 10 px or 10 ppt
	    bindsym Down resize grow height 10 px or 10 ppt
	    bindsym Up resize shrink height 10 px or 10 ppt
	    bindsym Right resize grow width 10 px or 10 ppt
	    bindsym Return mode default
	    bindsym Escape mode default
	}
EOF
tee "${HOME}/.i3/config.d/20-display" <<-EOF
	exec --no-startup-id \${HOME}/.i3/display
	bindsym \$mod+Shift+d exec --no-startup-id \${HOME}/.i3/display
EOF
tee "${HOME}/.i3/config.d/30-status" <<-EOF
	bar {
	    status_command i3status -c \${HOME}/.i3/status
	    position bottom
	    strip_workspace_numbers yes

	    colors {
	        background    #444444
	        statusline    #F8F8F8
	        separator     #707070
	        focused_workspace     #F8F8F8    #707070    #F8F8F8
	        active_workspace      #F8F8F8    #707070    #F8F8F8
	        inactive_workspace    #707070    #444444    #F8F8F8
	        urgent_workspace      #707070    #F92472    #F8F8F8
	    }
	}
EOF
tee "${HOME}/.i3/config.d/40-volume" <<-EOF
	bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -1%
	bindsym \$mod+minus exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -1%
	bindsym \$mod+Shift+minus exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10%
	bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +1%
	bindsym \$mod+plus exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +1%
	bindsym \$mod+Shift+plus exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10%
	bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle
	bindsym \$mod+numbersign exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle
	exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ 95%
	exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ 1
EOF
tee "${HOME}/.i3/config.d/60-slock" <<-EOF
	exec --no-startup-id xss-lock slock
	bindsym --release \$mod+l exec --no-startup-id slock xset dpms force off
EOF
tee "${HOME}/.i3/config.d/61-numlockx" <<-EOF
	exec --no-startup-id numlockx on
EOF
tee "${HOME}/.i3/config.d/62-screenshot" <<-EOF
	bindsym Print exec --no-startup-id screenshot
	bindsym --release Shift+Print exec --no-startup-id screenshot --select --clipboard
EOF
tee "${HOME}/.i3/config.d/63-dunst" <<-EOF
	exec --no-startup-id dunst -config \${HOME}/.i3/dunst -history_key mod4+j
EOF

mkdir -p "${HOME}/.i3/status.d"
tee "${HOME}/.i3/status.d/10-default" <<-EOF
	general {
	    colors = true
	    color_good = "#A6E22C"
	    color_degraded = "#707070"
	    color_bad = "#F92472"
	    interval = 5
	}
EOF
tee "${HOME}/.i3/status.d/20-volume" <<-EOF
	order += "volume master"
	volume master {
	    format = "%volume"
	    format_muted = "mute"
	    device = "default"
	    mixer = "Master"
	    mixer_idx = 0
	}
EOF
tee "${HOME}/.i3/status.d/30-disk" <<-EOF
	order += "disk /"
	disk / {
	    format = "%free"
	}
EOF
if [[ "${NIC}" == w* ]]
	then
		tee "${HOME}/.i3/status.d/60-wlan" <<-EOF
			order += "wireless ${NIC}"
			wireless ${NIC} {
			    format_up = "%essid"
			    format_down = "🖧"
			}
		EOF
	else
		tee "${HOME}/.i3/status.d/70-ethernet" <<-EOF
			order += "ethernet ${NIC}"
			ethernet ${NIC} {
			    format_up = "%ip"
			    format_down = "🖧"
			}
		EOF
fi
tee "${HOME}/.i3/status.d/90-time" <<-EOF
	order += "tztime local"
	tztime local {
	    format = "%Y-%m-%d %H:%M"
	}
EOF

tee "${HOME}/.i3/dunst" <<-EOF
	[global]
	    geometry="300x1-10-35"
	    padding = 10
	    horizontal_padding = 10
	    frame_width = 1
	    font = "Source Code Pro 10"
	    line_height = 3
	    format = "<b>%s</b>\n%b"
	    word_wrap = true
	    hide_duplicate_count = true
	    show_indicators = false

	[urgency_low]
	    background = "#444444"
	    foreground = "#F8F8F8"
	    frame_color = "#707070"
	    timeout = 3

	[urgency_normal]
	    background = "#444444"
	    foreground = "#F8F8F8"
	    frame_color = "#2AA198"
	    timeout = 10

	[urgency_critical]
	    background = "#444444"
	    foreground = "#F8F8F8"
	    frame_color = "#F92472"
	    timeout = 0
EOF

mkdir -p "${HOME}/.config/pcmanfm/default"
tee "${HOME}/.config/pcmanfm/default/pcmanfm.conf" <<-EOF
	[volume]
	autorun=0
	mount_on_startup=0
	mount_removable=0

	[ui]
	view_mode=compact
EOF
mkdir -p "${HOME}/.config/libfm"
tee "${HOME}/.config/libfm/libfm.conf" <<-EOF
	[config]
	terminal=xterm

	[places]
	places_applications=0
	places_computer=0
	places_desktop=0
	places_home=1
	places_network=0
	places_root=1
	places_trash=1
	places_unmounted=1
EOF

firefox -headless -CreateProfile "${USER} ${HOME}/.mozilla/firefox/${USER}"
timeout --signal=SIGUSR1 1 firefox -headless -P "${USER}"
tee "${HOME}/.mozilla/firefox/${USER}/prefs.js" <<-EOF
	user_pref("app.shield.optoutstudies.enabled", false);
	user_pref("app.update.auto", false);
	user_pref("app.update.enabled", false);
	user_pref("browser.bookmarks.autoExportHTML", true);
	user_pref("browser.contentblocking.category", "strict");
	user_pref("browser.download.useDownloadDir", false);
	user_pref("browser.formfill.enable", false);
	user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons", false);
	user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features", false);
	user_pref("browser.newtabpage.activity-stream.feeds.section.highlights", false);
	user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
	user_pref("browser.newtabpage.activity-stream.section.highlights.includeBookmarks", false);
	user_pref("browser.newtabpage.activity-stream.section.highlights.includeDownloads", false);
	user_pref("browser.newtabpage.activity-stream.section.highlights.includePocket", false);
	user_pref("browser.newtabpage.activity-stream.section.highlights.includeVisited", false);
	user_pref("browser.newtabpage.enabled", false);
	user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[],\"version\":1}");
	user_pref("browser.safebrowsing.downloads.enabled", false);
	user_pref("browser.safebrowsing.downloads.remote.block_potentially_unwanted", false);
	user_pref("browser.safebrowsing.downloads.remote.block_uncommon", false);
	user_pref("browser.safebrowsing.malware.enabled", false);
	user_pref("browser.safebrowsing.phishing.enabled", false);
	user_pref("browser.search.suggest.enabled", false);
	user_pref("browser.search.update", false);
	user_pref("browser.shell.checkDefaultBrowser", false);
	user_pref("browser.startup.homepage", "https://www.google.de/");
	user_pref("browser.uiCustomization.state", "{\"currentVersion\":16,\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"newElementCount\":0,\"placements\":{\"PersonalToolbar\":[\"personal-bookmarks\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"urlbar-container\",\"downloads-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"widget-overflow-fixed-list\":[]},\"seen\":[\"developer-button\"]}");
	user_pref("browser.urlbar.searchSuggestionsChoice", false);
	user_pref("browser.urlbar.suggest.history", false);
	user_pref("browser.urlbar.suggest.openpage", false);
	user_pref("browser.urlbar.suggest.searches", false);
	user_pref("datareporting.healthreport.uploadEnabled", false);
	user_pref("font.name.monospace.x-western", "Source Code Pro");
	user_pref("font.name.sans-serif.x-western", "Source Sans Pro");
	user_pref("font.name.serif.x-western", "Source Serif Pro");
	user_pref("general.smoothScroll", false);
	user_pref("intl.accept_languages", "de,de-de,en,en-us");
	user_pref("lightweightThemes.selectedThemeID", "firefox-compact-light@mozilla.org");
	user_pref("media.videocontrols.picture-in-picture.video-toggle.enabled", false);
	user_pref("network.cookie.cookieBehavior", 4);
	user_pref("permissions.default.camera", 2);
	user_pref("permissions.default.desktop-notification", 2);
	user_pref("permissions.default.geo", 2);
	user_pref("permissions.default.microphone", 2);
	user_pref("permissions.default.xr", 2);
	user_pref("privacy.cpd.offlineApps", true);
	user_pref("privacy.cpd.siteSettings", true);
	user_pref("privacy.donottrackheader.enabled", true);
	user_pref("privacy.history.custom", true);
	user_pref("privacy.sanitize.timeSpan", 0);
	user_pref("privacy.trackingprotection.enabled", true);
	user_pref("signon.autofillForms", false);
	user_pref("signon.generation.enabled", false);
	user_pref("signon.management.page.breach-alerts.enabled", false);
	user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
EOF

thunderbird -headless -CreateProfile "${USER} ${HOME}/.thunderbird/${USER}"
timeout --signal=SIGUSR1 1 thunderbird -headless -P "${USER}"
tee "${HOME}/.thunderbird/${USER}/prefs.js" <<-EOF
	user_pref("font.name.monospace.x-western", "Source Code Pro");
	user_pref("font.name.sans-serif.x-western", "Source Sans Pro");
	user_pref("font.name.serif.x-western", "Source Serif Pro");
	user_pref("lightweightThemes.selectedThemeID", "thunderbird-compact-light@mozilla.org");
	user_pref("mail.biff.play_sound", false);
	user_pref("mail.chat.play_sound", false);
	user_pref("mail.chat.show_desktop_notifications", false);
	user_pref("mail.collect_email_address_outgoing", false);
	user_pref("mail.compose.big_attachments.notify", false);
	user_pref("mail.enable_autocomplete", false);
	user_pref("mail.phishing.detection.enabled", false);
	user_pref("mail.prompt_purge_threshhold", false);
	user_pref("mail.shell.checkDefaultClient", false);
	user_pref("mail.showCondensedAddresses", false);
	user_pref("mailnews.database.global.indexer.enabled", false);
	user_pref("mailnews.start_page.enabled", false);
	user_pref("mailnews.start_page.url", "");
	user_pref("messenger.startup.action", 0);
	user_pref("messenger.status.awayWhenIdle", false);
	user_pref("messenger.status.reportIdle", false);
	user_pref("network.cookie.cookieBehavior", 1);
	user_pref("network.cookie.lifetimePolicy", 2);
	user_pref("places.history.enabled", false);
	user_pref("privacy.donottrackheader.enabled", true);
	user_pref("purple.conversations.im.send_typing", false);
	user_pref("spellchecker.dictionary", "de-DE");
	user_pref("toolkit.telemetry.prompted", 2);
	user_pref("toolkit.telemetry.rejected", true);
EOF
tee "${HOME}/.thunderbird/${USER}/xulstore.json" <<-EOF
	{"chrome://messenger/content/messenger.xul":{"mail-bar3":{"currentset":"button-getmsg,button-newmsg,button-address,separator,qfb-show-filter-bar,spring,button-appmenu"},"mail-toolbar-menubar2":{"autohide":"true"}}}
EOF
tee "${HOME}/.thunderbird/Crash Reports/crashreporter.ini" <<-EOF
	[Crash Reporter]
	SubmitReport=0
EOF

mkdir -p "${HOME}/.config/sublime-text-3/Packages/User"
unzip -p "/opt/sublime_text_3/Packages/Color Scheme - Default.sublime-package" Monokai.sublime-color-scheme \
| sed "s/\"black\": \"hsl(0, 0%, 0%)\"/\"black\": \"rgb(0, 0, 0)\"/g" \
| sed "s/\"black2\": \"hsl(60, 17%, 11%)\"/\"black2\": \"rgb(32, 32, 32)\"/g" \
| sed "s/\"black3\": \"hsl(70, 8%, 15%)\"/\"black3\": \"rgb(39, 39, 39)\"/g" \
| sed "s/\"blue\": \"hsl(190, 81%, 67%)\"/\"blue\": \"rgb(103, 216, 239)\"/g" \
| sed "s/\"grey\": \"hsl(55, 8%, 26%)\"/\"grey\": \"rgb(70, 70, 70)\"/g" \
| sed "s/\"orange\": \"hsl(32, 98%, 56%)\"/\"orange\": \"rgb(253, 150, 33)\"/g" \
| sed "s/\"orange2\": \"hsl(30, 83%, 34%)\"/\"orange2\": \"rgb(159, 87, 15)\"/g" \
| sed "s/\"orange3\": \"hsl(47, 100%, 79%)\"/\"orange3\": \"rgb(255, 232, 148)\"/g" \
| sed "s/\"purple\": \"hsl(261, 100%, 75%)\"/\"purple\": \"rgb(172, 128, 255)\"/g" \
| sed "s/\"red\": \"hsl(0, 93%, 59%)\"/\"red\": \"rgb(248, 53, 53)\"/g" \
| sed "s/\"red2\": \"hsl(338, 95%, 56%)\"/\"red2\": \"rgb(249, 36, 114)\"/g" \
| sed "s/\"white\": \"hsl(0, 0%, 97%)\"/\"white\": \"rgb(248, 248, 248)\"/g" \
| sed "s/\"white2\": \"hsl(60, 36%, 96%)\"/\"white2\": \"rgb(248, 248, 248)\"/g" \
| sed "s/\"white3\": \"hsl(60, 30%, 96%)\"/\"white3\": \"rgb(248, 248, 248)\"/g" \
| sed "s/\"yellow\": \"hsl(54, 70%, 68%)\"/\"yellow\": \"rgb(241, 250, 140)\"/g" \
| sed "s/\"yellow2\": \"hsl(80, 76%, 53%)\"/\"yellow2\": \"rgb(166, 226, 44)\"/g" \
| sed "s/\"yellow3\": \"hsl(60, 12%, 79%)\"/\"yellow3\": \"rgb(207, 207, 207)\"/g" \
| sed "s/\"yellow4\": \"hsl(55, 11%, 22%)\"/\"yellow4\": \"rgb(60, 60, 60)\"/g" \
| sed "s/\"yellow5\": \"hsl(50, 11%, 41%)\"/\"yellow5\": \"rgb(112, 112, 112)\"/g" \
| sed "s/\"name\": \"Monokai\"/\"name\": \"Felix\"/g" \
| sed "s/\"author\": \"Sublime HQ Pty Ltd, Wimer Hazenberg\"/\"author\": \"Auf zum Atem!\"/g" \
| sed "s/Monokai/Felix/g" > "${HOME}/.config/sublime-text-3/Packages/User/Felix.sublime-color-scheme"
tee "${HOME}/.config/sublime-text-3/Packages/User/Preferences.sublime-settings" <<-EOF
	{
	    "color_scheme": "Packages/User/Felix.sublime-color-scheme",
	    "draw_white_space": "all",
	    "ensure_newline_at_eof_on_save": true,
	    "fallback_encoding": "ISO 8859-1",
	    "font_face": "Source Code Pro",
	    "font_size": 14,
	    "highlight_line": true,
	    "highlight_modified_tabs": true,
	    "hot_exit": false,
	    "line_padding_bottom": 3,
	    "line_padding_top": 3,
	    "scroll_speed": 0,
	    "show_encoding": true,
	    "show_line_endings": true,
	    "trim_trailing_white_space_on_save": true
	}
EOF
tee "${HOME}/.config/sublime-text-3/Packages/User/Default (Linux).sublime-keymap" <<-EOF
	[
	    { "keys": ["ctrl+7"], "command": "toggle_comment", "args": { "block": false } },
	    { "keys": ["ctrl+shift+7"], "command": "toggle_comment", "args": { "block": true } }
	]
EOF
mkdir -p "${HOME}/.config/sublime-text-3/Local"
tee "${HOME}/.config/sublime-text-3/Local/Session.sublime_session" <<-EOF
	{"windows":[{"menu_visible": false}]}
EOF

mkdir -p "${HOME}/.config/GIMP/2.10"
tee "${HOME}/.config/GIMP/2.10/gimprc" <<-EOF
	(theme "System")
	(icon-theme "Color")
EOF

mkdir "${HOME}/.config/mpv"
tee "${HOME}/.config/mpv/config" <<-EOF
	stop-screensaver=yes
EOF

chmod -R g-rwx "${HOME}/"
chmod -R o-rwx "${HOME}/"

MANUFACTURER="$(sudo dmidecode -s system-manufacturer)"
if [ "${MANUFACTURER}" = "QEMU" ]
	then
		sudo pacman --sync --noconfirm spice-vdagent
		tee "${HOME}/.i3/config.d/21-spice" <<-EOF
			exec --no-startup-id spice-vdagent
		EOF
fi
