#!/bin/bash

set -x

sudo /bin/true || exit 1

PACKAGES=(
	dnsmasq
	ebtables
	libvirt
	openbsd-netcat
	qemu
	virt-manager
)
sudo pacman -Syu --noconfirm ${PACKAGES[*]}

sudo systemctl enable libvirtd.service
sudo usermod -a -G libvirt "${USER}"
